### ISSUE TITLE
suppression formation ou exp pro ne fonctionne pas

### ISSUE THREAD

**Issue by maurerleo** [AliasPedroKarim/KarimAndCo_Composant4#1]
Quand je me suis trompé sur l'insertion d'un nouveau panel, je ne peux plus le supprimerS

**Comment by pedrokarim** [comment]
Merci d'avoir signalé ce bug, je vous informe aujourd'hui qu'il a été fixée au commit [#71](https://github.com/AliasPedroKarim/KarimAndCo_Composant4/tree/2c59c0b9c5104e5e9891098285293028e36dd173)
